//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendEmailWebService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendEmailWebService.ServiceSoap")]
    public interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNotification", ReplyAction="*")]
        System.Threading.Tasks.Task<SendEmailWebService.SendNotificationResponse> SendNotificationAsync(SendEmailWebService.SendNotificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmailWithAttach", ReplyAction="*")]
        System.Threading.Tasks.Task<SendEmailWebService.SendEmailWithAttachResponse> SendEmailWithAttachAsync(SendEmailWebService.SendEmailWithAttachRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmailWithPriority", ReplyAction="*")]
        System.Threading.Tasks.Task<SendEmailWebService.SendEmailWithPriorityResponse> SendEmailWithPriorityAsync(SendEmailWebService.SendEmailWithPriorityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendNotificationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendNotification", Namespace="http://tempuri.org/", Order=0)]
        public SendEmailWebService.SendNotificationRequestBody Body;
        
        public SendNotificationRequest()
        {
        }
        
        public SendNotificationRequest(SendEmailWebService.SendNotificationRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendNotificationRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string projectName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageSubject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string messageBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SendEmailWebService.ArrayOfString listOfRecipients;
        
        public SendNotificationRequestBody()
        {
        }
        
        public SendNotificationRequestBody(string projectName, string code, string messageSubject, string messageBody, SendEmailWebService.ArrayOfString listOfRecipients)
        {
            this.projectName = projectName;
            this.code = code;
            this.messageSubject = messageSubject;
            this.messageBody = messageBody;
            this.listOfRecipients = listOfRecipients;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendNotificationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendNotificationResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendEmailWebService.SendNotificationResponseBody Body;
        
        public SendNotificationResponse()
        {
        }
        
        public SendNotificationResponse(SendEmailWebService.SendNotificationResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendNotificationResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendNotificationResult;
        
        public SendNotificationResponseBody()
        {
        }
        
        public SendNotificationResponseBody(bool SendNotificationResult)
        {
            this.SendNotificationResult = SendNotificationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailWithAttachRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailWithAttach", Namespace="http://tempuri.org/", Order=0)]
        public SendEmailWebService.SendEmailWithAttachRequestBody Body;
        
        public SendEmailWithAttachRequest()
        {
        }
        
        public SendEmailWithAttachRequest(SendEmailWebService.SendEmailWithAttachRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailWithAttachRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string projectName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageSubject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string messageBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SendEmailWebService.ArrayOfString listOfRecipients;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string attachmentFilePath;
        
        public SendEmailWithAttachRequestBody()
        {
        }
        
        public SendEmailWithAttachRequestBody(string projectName, string code, string messageSubject, string messageBody, SendEmailWebService.ArrayOfString listOfRecipients, string attachmentFilePath)
        {
            this.projectName = projectName;
            this.code = code;
            this.messageSubject = messageSubject;
            this.messageBody = messageBody;
            this.listOfRecipients = listOfRecipients;
            this.attachmentFilePath = attachmentFilePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailWithAttachResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailWithAttachResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendEmailWebService.SendEmailWithAttachResponseBody Body;
        
        public SendEmailWithAttachResponse()
        {
        }
        
        public SendEmailWithAttachResponse(SendEmailWebService.SendEmailWithAttachResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailWithAttachResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendEmailWithAttachResult;
        
        public SendEmailWithAttachResponseBody()
        {
        }
        
        public SendEmailWithAttachResponseBody(bool SendEmailWithAttachResult)
        {
            this.SendEmailWithAttachResult = SendEmailWithAttachResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailWithPriorityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailWithPriority", Namespace="http://tempuri.org/", Order=0)]
        public SendEmailWebService.SendEmailWithPriorityRequestBody Body;
        
        public SendEmailWithPriorityRequest()
        {
        }
        
        public SendEmailWithPriorityRequest(SendEmailWebService.SendEmailWithPriorityRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailWithPriorityRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string projectName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageSubject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string messageBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SendEmailWebService.ArrayOfString listOfRecipients;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<int> messagePriority;
        
        public SendEmailWithPriorityRequestBody()
        {
        }
        
        public SendEmailWithPriorityRequestBody(string projectName, string code, string messageSubject, string messageBody, SendEmailWebService.ArrayOfString listOfRecipients, System.Nullable<int> messagePriority)
        {
            this.projectName = projectName;
            this.code = code;
            this.messageSubject = messageSubject;
            this.messageBody = messageBody;
            this.listOfRecipients = listOfRecipients;
            this.messagePriority = messagePriority;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailWithPriorityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailWithPriorityResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendEmailWebService.SendEmailWithPriorityResponseBody Body;
        
        public SendEmailWithPriorityResponse()
        {
        }
        
        public SendEmailWithPriorityResponse(SendEmailWebService.SendEmailWithPriorityResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailWithPriorityResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendEmailWithPriorityResult;
        
        public SendEmailWithPriorityResponseBody()
        {
        }
        
        public SendEmailWithPriorityResponseBody(bool SendEmailWithPriorityResult)
        {
            this.SendEmailWithPriorityResult = SendEmailWithPriorityResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ServiceSoapChannel : SendEmailWebService.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SendEmailWebService.ServiceSoap>, SendEmailWebService.ServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendEmailWebService.SendNotificationResponse> SendEmailWebService.ServiceSoap.SendNotificationAsync(SendEmailWebService.SendNotificationRequest request)
        {
            return base.Channel.SendNotificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendEmailWebService.SendNotificationResponse> SendNotificationAsync(string projectName, string code, string messageSubject, string messageBody, SendEmailWebService.ArrayOfString listOfRecipients)
        {
            SendEmailWebService.SendNotificationRequest inValue = new SendEmailWebService.SendNotificationRequest();
            inValue.Body = new SendEmailWebService.SendNotificationRequestBody();
            inValue.Body.projectName = projectName;
            inValue.Body.code = code;
            inValue.Body.messageSubject = messageSubject;
            inValue.Body.messageBody = messageBody;
            inValue.Body.listOfRecipients = listOfRecipients;
            return ((SendEmailWebService.ServiceSoap)(this)).SendNotificationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendEmailWebService.SendEmailWithAttachResponse> SendEmailWebService.ServiceSoap.SendEmailWithAttachAsync(SendEmailWebService.SendEmailWithAttachRequest request)
        {
            return base.Channel.SendEmailWithAttachAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendEmailWebService.SendEmailWithAttachResponse> SendEmailWithAttachAsync(string projectName, string code, string messageSubject, string messageBody, SendEmailWebService.ArrayOfString listOfRecipients, string attachmentFilePath)
        {
            SendEmailWebService.SendEmailWithAttachRequest inValue = new SendEmailWebService.SendEmailWithAttachRequest();
            inValue.Body = new SendEmailWebService.SendEmailWithAttachRequestBody();
            inValue.Body.projectName = projectName;
            inValue.Body.code = code;
            inValue.Body.messageSubject = messageSubject;
            inValue.Body.messageBody = messageBody;
            inValue.Body.listOfRecipients = listOfRecipients;
            inValue.Body.attachmentFilePath = attachmentFilePath;
            return ((SendEmailWebService.ServiceSoap)(this)).SendEmailWithAttachAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendEmailWebService.SendEmailWithPriorityResponse> SendEmailWebService.ServiceSoap.SendEmailWithPriorityAsync(SendEmailWebService.SendEmailWithPriorityRequest request)
        {
            return base.Channel.SendEmailWithPriorityAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendEmailWebService.SendEmailWithPriorityResponse> SendEmailWithPriorityAsync(string projectName, string code, string messageSubject, string messageBody, SendEmailWebService.ArrayOfString listOfRecipients, System.Nullable<int> messagePriority)
        {
            SendEmailWebService.SendEmailWithPriorityRequest inValue = new SendEmailWebService.SendEmailWithPriorityRequest();
            inValue.Body = new SendEmailWebService.SendEmailWithPriorityRequestBody();
            inValue.Body.projectName = projectName;
            inValue.Body.code = code;
            inValue.Body.messageSubject = messageSubject;
            inValue.Body.messageBody = messageBody;
            inValue.Body.listOfRecipients = listOfRecipients;
            inValue.Body.messagePriority = messagePriority;
            return ((SendEmailWebService.ServiceSoap)(this)).SendEmailWithPriorityAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://sendemailwsraz.telekom.rs/Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://sendemailwsraz.telekom.rs/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
