//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendEmailService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendEmailService.ServiceSoap")]
    public interface ServiceSoap
    {
        
        // CODEGEN: Generating message contract since element name projectName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNotification", ReplyAction="*")]
        SendEmailService.SendNotificationResponse SendNotification(SendEmailService.SendNotificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNotification", ReplyAction="*")]
        System.Threading.Tasks.Task<SendEmailService.SendNotificationResponse> SendNotificationAsync(SendEmailService.SendNotificationRequest request);
        
        // CODEGEN: Generating message contract since element name projectName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmailWithAttach", ReplyAction="*")]
        SendEmailService.SendEmailWithAttachResponse SendEmailWithAttach(SendEmailService.SendEmailWithAttachRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmailWithAttach", ReplyAction="*")]
        System.Threading.Tasks.Task<SendEmailService.SendEmailWithAttachResponse> SendEmailWithAttachAsync(SendEmailService.SendEmailWithAttachRequest request);
        
        // CODEGEN: Generating message contract since element name projectName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmailWithPriority", ReplyAction="*")]
        SendEmailService.SendEmailWithPriorityResponse SendEmailWithPriority(SendEmailService.SendEmailWithPriorityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmailWithPriority", ReplyAction="*")]
        System.Threading.Tasks.Task<SendEmailService.SendEmailWithPriorityResponse> SendEmailWithPriorityAsync(SendEmailService.SendEmailWithPriorityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendNotificationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendNotification", Namespace="http://tempuri.org/", Order=0)]
        public SendEmailService.SendNotificationRequestBody Body;
        
        public SendNotificationRequest()
        {
        }
        
        public SendNotificationRequest(SendEmailService.SendNotificationRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendNotificationRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string projectName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageSubject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string messageBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SendEmailService.ArrayOfString listOfRecipients;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public SendEmailService.ArrayOfString listOfCC;
        
        public SendNotificationRequestBody()
        {
        }
        
        public SendNotificationRequestBody(string projectName, string code, string messageSubject, string messageBody, SendEmailService.ArrayOfString listOfRecipients, SendEmailService.ArrayOfString listOfCC)
        {
            this.projectName = projectName;
            this.code = code;
            this.messageSubject = messageSubject;
            this.messageBody = messageBody;
            this.listOfRecipients = listOfRecipients;
            this.listOfCC = listOfCC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendNotificationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendNotificationResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendEmailService.SendNotificationResponseBody Body;
        
        public SendNotificationResponse()
        {
        }
        
        public SendNotificationResponse(SendEmailService.SendNotificationResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendNotificationResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendNotificationResult;
        
        public SendNotificationResponseBody()
        {
        }
        
        public SendNotificationResponseBody(bool SendNotificationResult)
        {
            this.SendNotificationResult = SendNotificationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailWithAttachRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailWithAttach", Namespace="http://tempuri.org/", Order=0)]
        public SendEmailService.SendEmailWithAttachRequestBody Body;
        
        public SendEmailWithAttachRequest()
        {
        }
        
        public SendEmailWithAttachRequest(SendEmailService.SendEmailWithAttachRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailWithAttachRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string projectName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageSubject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string messageBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SendEmailService.ArrayOfString listOfRecipients;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public SendEmailService.ArrayOfString listOfCC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string attachmentFilePath;
        
        public SendEmailWithAttachRequestBody()
        {
        }
        
        public SendEmailWithAttachRequestBody(string projectName, string code, string messageSubject, string messageBody, SendEmailService.ArrayOfString listOfRecipients, SendEmailService.ArrayOfString listOfCC, string attachmentFilePath)
        {
            this.projectName = projectName;
            this.code = code;
            this.messageSubject = messageSubject;
            this.messageBody = messageBody;
            this.listOfRecipients = listOfRecipients;
            this.listOfCC = listOfCC;
            this.attachmentFilePath = attachmentFilePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailWithAttachResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailWithAttachResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendEmailService.SendEmailWithAttachResponseBody Body;
        
        public SendEmailWithAttachResponse()
        {
        }
        
        public SendEmailWithAttachResponse(SendEmailService.SendEmailWithAttachResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailWithAttachResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendEmailWithAttachResult;
        
        public SendEmailWithAttachResponseBody()
        {
        }
        
        public SendEmailWithAttachResponseBody(bool SendEmailWithAttachResult)
        {
            this.SendEmailWithAttachResult = SendEmailWithAttachResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailWithPriorityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailWithPriority", Namespace="http://tempuri.org/", Order=0)]
        public SendEmailService.SendEmailWithPriorityRequestBody Body;
        
        public SendEmailWithPriorityRequest()
        {
        }
        
        public SendEmailWithPriorityRequest(SendEmailService.SendEmailWithPriorityRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailWithPriorityRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string projectName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageSubject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string messageBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public SendEmailService.ArrayOfString listOfRecipients;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public SendEmailService.ArrayOfString listOfCC;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<int> messagePriority;
        
        public SendEmailWithPriorityRequestBody()
        {
        }
        
        public SendEmailWithPriorityRequestBody(string projectName, string code, string messageSubject, string messageBody, SendEmailService.ArrayOfString listOfRecipients, SendEmailService.ArrayOfString listOfCC, System.Nullable<int> messagePriority)
        {
            this.projectName = projectName;
            this.code = code;
            this.messageSubject = messageSubject;
            this.messageBody = messageBody;
            this.listOfRecipients = listOfRecipients;
            this.listOfCC = listOfCC;
            this.messagePriority = messagePriority;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailWithPriorityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailWithPriorityResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendEmailService.SendEmailWithPriorityResponseBody Body;
        
        public SendEmailWithPriorityResponse()
        {
        }
        
        public SendEmailWithPriorityResponse(SendEmailService.SendEmailWithPriorityResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailWithPriorityResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendEmailWithPriorityResult;
        
        public SendEmailWithPriorityResponseBody()
        {
        }
        
        public SendEmailWithPriorityResponseBody(bool SendEmailWithPriorityResult)
        {
            this.SendEmailWithPriorityResult = SendEmailWithPriorityResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ServiceSoapChannel : SendEmailService.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SendEmailService.ServiceSoap>, SendEmailService.ServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendEmailService.SendNotificationResponse SendEmailService.ServiceSoap.SendNotification(SendEmailService.SendNotificationRequest request)
        {
            return base.Channel.SendNotification(request);
        }
        
        public bool SendNotification(string projectName, string code, string messageSubject, string messageBody, SendEmailService.ArrayOfString listOfRecipients, SendEmailService.ArrayOfString listOfCC)
        {
            SendEmailService.SendNotificationRequest inValue = new SendEmailService.SendNotificationRequest();
            inValue.Body = new SendEmailService.SendNotificationRequestBody();
            inValue.Body.projectName = projectName;
            inValue.Body.code = code;
            inValue.Body.messageSubject = messageSubject;
            inValue.Body.messageBody = messageBody;
            inValue.Body.listOfRecipients = listOfRecipients;
            inValue.Body.listOfCC = listOfCC;
            SendEmailService.SendNotificationResponse retVal = ((SendEmailService.ServiceSoap)(this)).SendNotification(inValue);
            return retVal.Body.SendNotificationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendEmailService.SendNotificationResponse> SendEmailService.ServiceSoap.SendNotificationAsync(SendEmailService.SendNotificationRequest request)
        {
            return base.Channel.SendNotificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendEmailService.SendNotificationResponse> SendNotificationAsync(string projectName, string code, string messageSubject, string messageBody, SendEmailService.ArrayOfString listOfRecipients, SendEmailService.ArrayOfString listOfCC)
        {
            SendEmailService.SendNotificationRequest inValue = new SendEmailService.SendNotificationRequest();
            inValue.Body = new SendEmailService.SendNotificationRequestBody();
            inValue.Body.projectName = projectName;
            inValue.Body.code = code;
            inValue.Body.messageSubject = messageSubject;
            inValue.Body.messageBody = messageBody;
            inValue.Body.listOfRecipients = listOfRecipients;
            inValue.Body.listOfCC = listOfCC;
            return ((SendEmailService.ServiceSoap)(this)).SendNotificationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendEmailService.SendEmailWithAttachResponse SendEmailService.ServiceSoap.SendEmailWithAttach(SendEmailService.SendEmailWithAttachRequest request)
        {
            return base.Channel.SendEmailWithAttach(request);
        }
        
        public bool SendEmailWithAttach(string projectName, string code, string messageSubject, string messageBody, SendEmailService.ArrayOfString listOfRecipients, SendEmailService.ArrayOfString listOfCC, string attachmentFilePath)
        {
            SendEmailService.SendEmailWithAttachRequest inValue = new SendEmailService.SendEmailWithAttachRequest();
            inValue.Body = new SendEmailService.SendEmailWithAttachRequestBody();
            inValue.Body.projectName = projectName;
            inValue.Body.code = code;
            inValue.Body.messageSubject = messageSubject;
            inValue.Body.messageBody = messageBody;
            inValue.Body.listOfRecipients = listOfRecipients;
            inValue.Body.listOfCC = listOfCC;
            inValue.Body.attachmentFilePath = attachmentFilePath;
            SendEmailService.SendEmailWithAttachResponse retVal = ((SendEmailService.ServiceSoap)(this)).SendEmailWithAttach(inValue);
            return retVal.Body.SendEmailWithAttachResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendEmailService.SendEmailWithAttachResponse> SendEmailService.ServiceSoap.SendEmailWithAttachAsync(SendEmailService.SendEmailWithAttachRequest request)
        {
            return base.Channel.SendEmailWithAttachAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendEmailService.SendEmailWithAttachResponse> SendEmailWithAttachAsync(string projectName, string code, string messageSubject, string messageBody, SendEmailService.ArrayOfString listOfRecipients, SendEmailService.ArrayOfString listOfCC, string attachmentFilePath)
        {
            SendEmailService.SendEmailWithAttachRequest inValue = new SendEmailService.SendEmailWithAttachRequest();
            inValue.Body = new SendEmailService.SendEmailWithAttachRequestBody();
            inValue.Body.projectName = projectName;
            inValue.Body.code = code;
            inValue.Body.messageSubject = messageSubject;
            inValue.Body.messageBody = messageBody;
            inValue.Body.listOfRecipients = listOfRecipients;
            inValue.Body.listOfCC = listOfCC;
            inValue.Body.attachmentFilePath = attachmentFilePath;
            return ((SendEmailService.ServiceSoap)(this)).SendEmailWithAttachAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendEmailService.SendEmailWithPriorityResponse SendEmailService.ServiceSoap.SendEmailWithPriority(SendEmailService.SendEmailWithPriorityRequest request)
        {
            return base.Channel.SendEmailWithPriority(request);
        }
        
        public bool SendEmailWithPriority(string projectName, string code, string messageSubject, string messageBody, SendEmailService.ArrayOfString listOfRecipients, SendEmailService.ArrayOfString listOfCC, System.Nullable<int> messagePriority)
        {
            SendEmailService.SendEmailWithPriorityRequest inValue = new SendEmailService.SendEmailWithPriorityRequest();
            inValue.Body = new SendEmailService.SendEmailWithPriorityRequestBody();
            inValue.Body.projectName = projectName;
            inValue.Body.code = code;
            inValue.Body.messageSubject = messageSubject;
            inValue.Body.messageBody = messageBody;
            inValue.Body.listOfRecipients = listOfRecipients;
            inValue.Body.listOfCC = listOfCC;
            inValue.Body.messagePriority = messagePriority;
            SendEmailService.SendEmailWithPriorityResponse retVal = ((SendEmailService.ServiceSoap)(this)).SendEmailWithPriority(inValue);
            return retVal.Body.SendEmailWithPriorityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendEmailService.SendEmailWithPriorityResponse> SendEmailService.ServiceSoap.SendEmailWithPriorityAsync(SendEmailService.SendEmailWithPriorityRequest request)
        {
            return base.Channel.SendEmailWithPriorityAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendEmailService.SendEmailWithPriorityResponse> SendEmailWithPriorityAsync(string projectName, string code, string messageSubject, string messageBody, SendEmailService.ArrayOfString listOfRecipients, SendEmailService.ArrayOfString listOfCC, System.Nullable<int> messagePriority)
        {
            SendEmailService.SendEmailWithPriorityRequest inValue = new SendEmailService.SendEmailWithPriorityRequest();
            inValue.Body = new SendEmailService.SendEmailWithPriorityRequestBody();
            inValue.Body.projectName = projectName;
            inValue.Body.code = code;
            inValue.Body.messageSubject = messageSubject;
            inValue.Body.messageBody = messageBody;
            inValue.Body.listOfRecipients = listOfRecipients;
            inValue.Body.listOfCC = listOfCC;
            inValue.Body.messagePriority = messagePriority;
            return ((SendEmailService.ServiceSoap)(this)).SendEmailWithPriorityAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://sendemailwsraz/Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://sendemailwsraz/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
