//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BizSMS.ldapCheckWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LDAPCheckSoap", Namespace="http://tempuri.org/")]
    public partial class LDAPCheck : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback vratiTipKorisnikaOperationCompleted;
        
        private System.Threading.SendOrPostCallback vratiTipBrojaOperationCompleted;
        
        private System.Threading.SendOrPostCallback vratiTipKorisnikaTempOperationCompleted;
        
        private System.Threading.SendOrPostCallback proveriKorisnikaPoAtributuOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LDAPCheck() {
            this.Url = global::BizSMS.Properties.Settings.Default.BizSMS_ldapCheckWS_LDAPCheck;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event vratiTipKorisnikaCompletedEventHandler vratiTipKorisnikaCompleted;
        
        /// <remarks/>
        public event vratiTipBrojaCompletedEventHandler vratiTipBrojaCompleted;
        
        /// <remarks/>
        public event vratiTipKorisnikaTempCompletedEventHandler vratiTipKorisnikaTempCompleted;
        
        /// <remarks/>
        public event proveriKorisnikaPoAtributuCompletedEventHandler proveriKorisnikaPoAtributuCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vratiTipKorisnika", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string vratiTipKorisnika(string msisdn) {
            object[] results = this.Invoke("vratiTipKorisnika", new object[] {
                        msisdn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void vratiTipKorisnikaAsync(string msisdn) {
            this.vratiTipKorisnikaAsync(msisdn, null);
        }
        
        /// <remarks/>
        public void vratiTipKorisnikaAsync(string msisdn, object userState) {
            if ((this.vratiTipKorisnikaOperationCompleted == null)) {
                this.vratiTipKorisnikaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvratiTipKorisnikaOperationCompleted);
            }
            this.InvokeAsync("vratiTipKorisnika", new object[] {
                        msisdn}, this.vratiTipKorisnikaOperationCompleted, userState);
        }
        
        private void OnvratiTipKorisnikaOperationCompleted(object arg) {
            if ((this.vratiTipKorisnikaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.vratiTipKorisnikaCompleted(this, new vratiTipKorisnikaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vratiTipBroja", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string vratiTipBroja(string msisdn, string token) {
            object[] results = this.Invoke("vratiTipBroja", new object[] {
                        msisdn,
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void vratiTipBrojaAsync(string msisdn, string token) {
            this.vratiTipBrojaAsync(msisdn, token, null);
        }
        
        /// <remarks/>
        public void vratiTipBrojaAsync(string msisdn, string token, object userState) {
            if ((this.vratiTipBrojaOperationCompleted == null)) {
                this.vratiTipBrojaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvratiTipBrojaOperationCompleted);
            }
            this.InvokeAsync("vratiTipBroja", new object[] {
                        msisdn,
                        token}, this.vratiTipBrojaOperationCompleted, userState);
        }
        
        private void OnvratiTipBrojaOperationCompleted(object arg) {
            if ((this.vratiTipBrojaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.vratiTipBrojaCompleted(this, new vratiTipBrojaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vratiTipKorisnikaTemp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string vratiTipKorisnikaTemp(string msisdn) {
            object[] results = this.Invoke("vratiTipKorisnikaTemp", new object[] {
                        msisdn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void vratiTipKorisnikaTempAsync(string msisdn) {
            this.vratiTipKorisnikaTempAsync(msisdn, null);
        }
        
        /// <remarks/>
        public void vratiTipKorisnikaTempAsync(string msisdn, object userState) {
            if ((this.vratiTipKorisnikaTempOperationCompleted == null)) {
                this.vratiTipKorisnikaTempOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvratiTipKorisnikaTempOperationCompleted);
            }
            this.InvokeAsync("vratiTipKorisnikaTemp", new object[] {
                        msisdn}, this.vratiTipKorisnikaTempOperationCompleted, userState);
        }
        
        private void OnvratiTipKorisnikaTempOperationCompleted(object arg) {
            if ((this.vratiTipKorisnikaTempCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.vratiTipKorisnikaTempCompleted(this, new vratiTipKorisnikaTempCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/proveriKorisnikaPoAtributu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string proveriKorisnikaPoAtributu(string msisdn, string atribut) {
            object[] results = this.Invoke("proveriKorisnikaPoAtributu", new object[] {
                        msisdn,
                        atribut});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void proveriKorisnikaPoAtributuAsync(string msisdn, string atribut) {
            this.proveriKorisnikaPoAtributuAsync(msisdn, atribut, null);
        }
        
        /// <remarks/>
        public void proveriKorisnikaPoAtributuAsync(string msisdn, string atribut, object userState) {
            if ((this.proveriKorisnikaPoAtributuOperationCompleted == null)) {
                this.proveriKorisnikaPoAtributuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnproveriKorisnikaPoAtributuOperationCompleted);
            }
            this.InvokeAsync("proveriKorisnikaPoAtributu", new object[] {
                        msisdn,
                        atribut}, this.proveriKorisnikaPoAtributuOperationCompleted, userState);
        }
        
        private void OnproveriKorisnikaPoAtributuOperationCompleted(object arg) {
            if ((this.proveriKorisnikaPoAtributuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.proveriKorisnikaPoAtributuCompleted(this, new proveriKorisnikaPoAtributuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void vratiTipKorisnikaCompletedEventHandler(object sender, vratiTipKorisnikaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class vratiTipKorisnikaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal vratiTipKorisnikaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void vratiTipBrojaCompletedEventHandler(object sender, vratiTipBrojaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class vratiTipBrojaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal vratiTipBrojaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void vratiTipKorisnikaTempCompletedEventHandler(object sender, vratiTipKorisnikaTempCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class vratiTipKorisnikaTempCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal vratiTipKorisnikaTempCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void proveriKorisnikaPoAtributuCompletedEventHandler(object sender, proveriKorisnikaPoAtributuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class proveriKorisnikaPoAtributuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal proveriKorisnikaPoAtributuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591