//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new contract.
        /// </summary>
        public static string AddContract {
            get {
                return ResourceManager.GetString("AddContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new message cost range.
        /// </summary>
        public static string AddMessageCost {
            get {
                return ResourceManager.GetString("AddMessageCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add number in group:.
        /// </summary>
        public static string AddNumber {
            get {
                return ResourceManager.GetString("AddNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add numbers to VPN group.
        /// </summary>
        public static string AddNumbersToVPN {
            get {
                return ResourceManager.GetString("AddNumbersToVPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add one number.
        /// </summary>
        public static string AddOneNumber {
            get {
                return ResourceManager.GetString("AddOneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected.
        /// </summary>
        public static string AddSelected {
            get {
                return ResourceManager.GetString("AddSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add number/s from VPN group.
        /// </summary>
        public static string AddVpnNumber {
            get {
                return ResourceManager.GetString("AddVpnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upload following numbers:.
        /// </summary>
        public static string AllowedNumbersForUpload {
            get {
                return ResourceManager.GetString("AllowedNumbersForUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow sending.
        /// </summary>
        public static string AllowSending {
            get {
                return ResourceManager.GetString("AllowSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphanumeric.
        /// </summary>
        public static string Alphanumeric {
            get {
                return ResourceManager.GetString("Alphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphanumeric can contain minimum 3 and maximum 11 english letters, numbers, space and special characters (- and _).
        /// </summary>
        public static string AlphanumericRegExValidation {
            get {
                return ResourceManager.GetString("AlphanumericRegExValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphanumerics.
        /// </summary>
        public static string Alphanumerics {
            get {
                return ResourceManager.GetString("Alphanumerics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists.
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This number already exists in the group, or the SMS sending to this number is denied due to unsubscription from service..
        /// </summary>
        public static string AlreadyExistsInGroup {
            get {
                return ResourceManager.GetString("AlreadyExistsInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to group.
        /// </summary>
        public static string BackToGroup {
            get {
                return ResourceManager.GetString("BackToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Groups.
        /// </summary>
        public static string BackToGroups {
            get {
                return ResourceManager.GetString("BackToGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to home page.
        /// </summary>
        public static string BackToHomePage {
            get {
                return ResourceManager.GetString("BackToHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad format numbers:.
        /// </summary>
        public static string BadFormatNumbers {
            get {
                return ResourceManager.GetString("BadFormatNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad group numbers:.
        /// </summary>
        public static string BadGroupNumbers {
            get {
                return ResourceManager.GetString("BadGroupNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request.
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server cannot or will not process the request due to an apparent client error.
        /// </summary>
        public static string BadRequestMessage {
            get {
                return ResourceManager.GetString("BadRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled by.
        /// </summary>
        public static string CanceledBy {
            get {
                return ResourceManager.GetString("CanceledBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelSending {
            get {
                return ResourceManager.GetString("CancelSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check numbers.
        /// </summary>
        public static string CheckNumbers {
            get {
                return ResourceManager.GetString("CheckNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose number from list.
        /// </summary>
        public static string ChooseNumberFromList {
            get {
                return ResourceManager.GetString("ChooseNumberFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client contracts.
        /// </summary>
        public static string ClientContracts {
            get {
                return ResourceManager.GetString("ClientContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client name.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client name is required.
        /// </summary>
        public static string ClientNameIsRequired {
            get {
                return ResourceManager.GetString("ClientNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client numbers.
        /// </summary>
        public static string ClientNumbers {
            get {
                return ResourceManager.GetString("ClientNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register client.
        /// </summary>
        public static string ClientRegister {
            get {
                return ResourceManager.GetString("ClientRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select client.
        /// </summary>
        public static string ClientSelectList {
            get {
                return ResourceManager.GetString("ClientSelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm numbers to upload.
        /// </summary>
        public static string ConfirmUploadNumbers {
            get {
                return ResourceManager.GetString("ConfirmUploadNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract number.
        /// </summary>
        public static string ContractID {
            get {
                return ResourceManager.GetString("ContractID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new client.
        /// </summary>
        public static string CreateClient {
            get {
                return ResourceManager.GetString("CreateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new group.
        /// </summary>
        public static string CreateGroup {
            get {
                return ResourceManager.GetString("CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Alphanumeric.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom groups.
        /// </summary>
        public static string CustomGroups {
            get {
                return ResourceManager.GetString("CustomGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated numbers.
        /// </summary>
        public static string DeactivatedNumbers {
            get {
                return ResourceManager.GetString("DeactivatedNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default groups.
        /// </summary>
        public static string DefaultGroups {
            get {
                return ResourceManager.GetString("DefaultGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete contract.
        /// </summary>
        public static string DeleteContract {
            get {
                return ResourceManager.GetString("DeleteContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        public static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of change | Date | Changed by admin.
        /// </summary>
        public static string DeniedReason {
            get {
                return ResourceManager.GetString("DeniedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny sending.
        /// </summary>
        public static string DenySending {
            get {
                return ResourceManager.GetString("DenySending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download template.
        /// </summary>
        public static string DownloadTemplate {
            get {
                return ResourceManager.GetString("DownloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate numbers found in uploaded list:.
        /// </summary>
        public static string DuplicateNumbers {
            get {
                return ResourceManager.GetString("DuplicateNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit contract.
        /// </summary>
        public static string EditContract {
            get {
                return ResourceManager.GetString("EditContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit group.
        /// </summary>
        public static string EditGroup {
            get {
                return ResourceManager.GetString("EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit number.
        /// </summary>
        public static string EditNumberInfo {
            get {
                return ResourceManager.GetString("EditNumberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter message.
        /// </summary>
        public static string EnterMessage {
            get {
                return ResourceManager.GetString("EnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name for this number.
        /// </summary>
        public static string EnterNameForNumber {
            get {
                return ResourceManager.GetString("EnterNameForNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code.
        /// </summary>
        public static string EnterVerificationCode {
            get {
                return ResourceManager.GetString("EnterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Please contact administrator..
        /// </summary>
        public static string ErrorContactAdmin {
            get {
                return ResourceManager.GetString("ErrorContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again later..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an error, please try again later. If this repeats please contact your administrator..
        /// </summary>
        public static string ErrorTryLaterContactAdmin {
            get {
                return ResourceManager.GetString("ErrorTryLaterContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number/s already exist in the group:.
        /// </summary>
        public static string ExistingNumbers {
            get {
                return ResourceManager.GetString("ExistingNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerik.
        /// </summary>
        public static string FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For group.
        /// </summary>
        public static string ForGroup {
            get {
                return ResourceManager.GetString("ForGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For month.
        /// </summary>
        public static string ForMonth {
            get {
                return ResourceManager.GetString("ForMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free of charge.
        /// </summary>
        public static string FreeOfCharge {
            get {
                return ResourceManager.GetString("FreeOfCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again. If problem persist, please contact administrator..
        /// </summary>
        public static string GetDataFail {
            get {
                return ResourceManager.GetString("GetDataFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported numbers count:.
        /// </summary>
        public static string ImportCount {
            get {
                return ResourceManager.GetString("ImportCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import numbers.
        /// </summary>
        public static string ImportNumbers {
            get {
                return ResourceManager.GetString("ImportNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import numbers to VPN group.
        /// </summary>
        public static string ImportNumbersToVPN {
            get {
                return ResourceManager.GetString("ImportNumbersToVPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS to numbers within and outside your Biznet group.
        /// </summary>
        public static string IndexText {
            get {
                return ResourceManager.GetString("IndexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In MTS.
        /// </summary>
        public static string InMTS {
            get {
                return ResourceManager.GetString("InMTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidCode.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is not a valid e-mail address.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is not a valid phone number.
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}.
        /// </summary>
        public static string IsNotGreaterThan {
            get {
                return ResourceManager.GetString("IsNotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string LengthValidation {
            get {
                return ResourceManager.GetString("LengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be {2} characters long..
        /// </summary>
        public static string LengthValidationOtp {
            get {
                return ResourceManager.GetString("LengthValidationOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List numbers.
        /// </summary>
        public static string ListNumbers {
            get {
                return ResourceManager.GetString("ListNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string LockedMessage {
            get {
                return ResourceManager.GetString("LockedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage clients.
        /// </summary>
        public static string ManageClients {
            get {
                return ResourceManager.GetString("ManageClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Manual.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of characters is 30 (including spaces).
        /// </summary>
        public static string MaxNumberOfCharacters {
            get {
                return ResourceManager.GetString("MaxNumberOfCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message has already been sent!.
        /// </summary>
        public static string MessageAlreadySent {
            get {
                return ResourceManager.GetString("MessageAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message cost.
        /// </summary>
        public static string MessageCost {
            get {
                return ResourceManager.GetString("MessageCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message length.
        /// </summary>
        public static string MessageLength {
            get {
                return ResourceManager.GetString("MessageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message will be sent to this group:.
        /// </summary>
        public static string MessageSentToGroup {
            get {
                return ResourceManager.GetString("MessageSentToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message will be sent to these numbers:.
        /// </summary>
        public static string MessageSentToNumbers {
            get {
                return ResourceManager.GetString("MessageSentToNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message text.
        /// </summary>
        public static string MessageText {
            get {
                return ResourceManager.GetString("MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly report.
        /// </summary>
        public static string MonthReport {
            get {
                return ResourceManager.GetString("MonthReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly report - detail.
        /// </summary>
        public static string MonthReportDetail {
            get {
                return ResourceManager.GetString("MonthReportDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTS ID.
        /// </summary>
        public static string MtsID {
            get {
                return ResourceManager.GetString("MtsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot have empty space or special characters.
        /// </summary>
        public static string NoEmptySpaceOrSpecChars {
            get {
                return ResourceManager.GetString("NoEmptySpaceOrSpecChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new numbers to update..
        /// </summary>
        public static string NoNewNumbersToUpdate {
            get {
                return ResourceManager.GetString("NoNewNumbersToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In your database there is no sender/alphanumeric defined in the format of a phone number which is needed for the SMS to be sent outside of MTS network. Please contact administrator to input one..
        /// </summary>
        public static string NoNumericSender {
            get {
                return ResourceManager.GetString("NoNumericSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in MTS.
        /// </summary>
        public static string NotInMTS {
            get {
                return ResourceManager.GetString("NotInMTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not sent.
        /// </summary>
        public static string NotSent {
            get {
                return ResourceManager.GetString("NotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number is deleted from the group!.
        /// </summary>
        public static string NumberDeleted {
            get {
                return ResourceManager.GetString("NumberDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of delivered sms messages.
        /// </summary>
        public static string NumberOfDeliveredMessages {
            get {
                return ResourceManager.GetString("NumberOfDeliveredMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total of delivered SMS (including multiple messages).
        /// </summary>
        public static string NumberOfDeliveredMessagesLength {
            get {
                return ResourceManager.GetString("NumberOfDeliveredMessagesLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of messages from.
        /// </summary>
        public static string NumberOfMessagesFrom {
            get {
                return ResourceManager.GetString("NumberOfMessagesFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of messages to.
        /// </summary>
        public static string NumberOfMessagesTo {
            get {
                return ResourceManager.GetString("NumberOfMessagesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sent messages.
        /// </summary>
        public static string NumberOfSentMessages {
            get {
                return ResourceManager.GetString("NumberOfSentMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sent sms messages.
        /// </summary>
        public static string NumberOfSentSMSes {
            get {
                return ResourceManager.GetString("NumberOfSentSMSes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        public static string Numbers {
            get {
                return ResourceManager.GetString("Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers in group.
        /// </summary>
        public static string NumbersInGroup {
            get {
                return ResourceManager.GetString("NumbersInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following number/s will be uploaded:.
        /// </summary>
        public static string NumbersToBeUploaded {
            get {
                return ResourceManager.GetString("NumbersToBeUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number type.
        /// </summary>
        public static string NumberType {
            get {
                return ResourceManager.GetString("NumberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected number type can not be added in choosen group..
        /// </summary>
        public static string NumberTypeIsNotBelong {
            get {
                return ResourceManager.GetString("NumberTypeIsNotBelong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out MTS.
        /// </summary>
        public static string OutMTS {
            get {
                return ResourceManager.GetString("OutMTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranges must not overlap with existing ones.
        /// </summary>
        public static string OverlapingRange {
            get {
                return ResourceManager.GetString("OverlapingRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page you are looking for doesn&apos;t exist.
        /// </summary>
        public static string PageNotExist {
            get {
                return ResourceManager.GetString("PageNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string PasswordChangedMessage {
            get {
                return ResourceManager.GetString("PasswordChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid phone number..
        /// </summary>
        public static string PhoneNotValid {
            get {
                return ResourceManager.GetString("PhoneNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required.
        /// </summary>
        public static string PhoneNumberIsRequired {
            get {
                return ResourceManager.GetString("PhoneNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend code.
        /// </summary>
        public static string PonoviKod {
            get {
                return ResourceManager.GetString("PonoviKod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (RSD).
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price can not be bigger then price with smaller range.
        /// </summary>
        public static string PriceError {
            get {
                return ResourceManager.GetString("PriceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price total (including multiple messages length).
        /// </summary>
        public static string PriceOfDeliveredMessagesLength {
            get {
                return ResourceManager.GetString("PriceOfDeliveredMessagesLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test123.
        /// </summary>
        public static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qued.
        /// </summary>
        public static string Qued {
            get {
                return ResourceManager.GetString("Qued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this scheduled SMS?.
        /// </summary>
        public static string QuestionCancelScheduledSMS {
            get {
                return ResourceManager.GetString("QuestionCancelScheduledSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this alphanumeric?.
        /// </summary>
        public static string QuestionDeleteAlphanumeric {
            get {
                return ResourceManager.GetString("QuestionDeleteAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this client?.
        /// </summary>
        public static string QuestionDeleteClient {
            get {
                return ResourceManager.GetString("QuestionDeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this group?.
        /// </summary>
        public static string QuestionDeleteGroup {
            get {
                return ResourceManager.GetString("QuestionDeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected message cost?.
        /// </summary>
        public static string QuestionDeleteMessageCost {
            get {
                return ResourceManager.GetString("QuestionDeleteMessageCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this number?.
        /// </summary>
        public static string QuestionDeleteNumber {
            get {
                return ResourceManager.GetString("QuestionDeleteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this user?.
        /// </summary>
        public static string QuestionDeleteUser {
            get {
                return ResourceManager.GetString("QuestionDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is message received and is it in correct format?.
        /// </summary>
        public static string QuestionSendTestMessage {
            get {
                return ResourceManager.GetString("QuestionSendTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By user:.
        /// </summary>
        public static string ReasonByUser {
            get {
                return ResourceManager.GetString("ReasonByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a deny sending reason!.
        /// </summary>
        public static string ReasonForDenySending {
            get {
                return ResourceManager.GetString("ReasonForDenySending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh numbers.
        /// </summary>
        public static string RefreshNumbers {
            get {
                return ResourceManager.GetString("RefreshNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh VPN numbers.
        /// </summary>
        public static string RefreshVPNnumbers {
            get {
                return ResourceManager.GetString("RefreshVPNnumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this browser?.
        /// </summary>
        public static string RememberBrowser {
            get {
                return ResourceManager.GetString("RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected.
        /// </summary>
        public static string RemoveSelected {
            get {
                return ResourceManager.GetString("RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS reports .
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field! Please insert a number in format: 06XXXXXXX.
        /// </summary>
        public static string RequiredNumberFormat {
            get {
                return ResourceManager.GetString("RequiredNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset client password.
        /// </summary>
        public static string ResetClientPassword {
            get {
                return ResourceManager.GetString("ResetClientPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is reseted successfuly.
        /// </summary>
        public static string ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        public static string Scheduled {
            get {
                return ResourceManager.GetString("Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled!.
        /// </summary>
        public static string ScheduledSendingCanceled {
            get {
                return ResourceManager.GetString("ScheduledSendingCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled SMS.
        /// </summary>
        public static string ScheduledSMS {
            get {
                return ResourceManager.GetString("ScheduledSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule sending.
        /// </summary>
        public static string ScheduleSending {
            get {
                return ResourceManager.GetString("ScheduleSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select client.
        /// </summary>
        public static string SelectClient {
            get {
                return ResourceManager.GetString("SelectClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected numbers.
        /// </summary>
        public static string SelectedNumbers {
            get {
                return ResourceManager.GetString("SelectedNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select number type.
        /// </summary>
        public static string SelectNumberType {
            get {
                return ResourceManager.GetString("SelectNumberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send allowed.
        /// </summary>
        public static string SendAllowed {
            get {
                return ResourceManager.GetString("SendAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send date.
        /// </summary>
        public static string SendDate {
            get {
                return ResourceManager.GetString("SendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number(s) that are not allowed to be added because they have unregistered from the list of SMS recepients: .
        /// </summary>
        public static string SendDeniedNumbers {
            get {
                return ResourceManager.GetString("SendDeniedNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending.
        /// </summary>
        public static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending test SMS.
        /// </summary>
        public static string SendingTestSMS {
            get {
                return ResourceManager.GetString("SendingTestSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string SendMonth {
            get {
                return ResourceManager.GetString("SendMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS.
        /// </summary>
        public static string SendSMS {
            get {
                return ResourceManager.GetString("SendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All messages are successfully added to send queue. You can check status on Sent SMS Report..
        /// </summary>
        public static string SendSMSDone {
            get {
                return ResourceManager.GetString("SendSMSDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS failed. Please try again later. If problem persist, please contact administrator..
        /// </summary>
        public static string SendSMSFail {
            get {
                return ResourceManager.GetString("SendSMSFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS To Group.
        /// </summary>
        public static string SendSMSToGroup {
            get {
                return ResourceManager.GetString("SendSMSToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send test SMS.
        /// </summary>
        public static string SendTestSMS {
            get {
                return ResourceManager.GetString("SendTestSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send test SMS failed. Please try again later. If problem persist, please contact administrator..
        /// </summary>
        public static string SendTestSMSFail {
            get {
                return ResourceManager.GetString("SendTestSMSFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this step.
        /// </summary>
        public static string SkipTestSMS {
            get {
                return ResourceManager.GetString("SkipTestSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string SMS {
            get {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent SMS report.
        /// </summary>
        public static string SMSReport {
            get {
                return ResourceManager.GetString("SMSReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS report - detail.
        /// </summary>
        public static string SMSReportDetail {
            get {
                return ResourceManager.GetString("SMSReportDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start sending.
        /// </summary>
        public static string StartSending {
            get {
                return ResourceManager.GetString("StartSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number/numbers successfully updated!.
        /// </summary>
        public static string SuccessNewNumbersUpdate {
            get {
                return ResourceManager.GetString("SuccessNewNumbersUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To number.
        /// </summary>
        public static string ToNumber {
            get {
                return ResourceManager.GetString("ToNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total of numbers.
        /// </summary>
        public static string TotalOfNumbers {
            get {
                return ResourceManager.GetString("TotalOfNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to view this page.
        /// </summary>
        public static string UnauthorizedMessage {
            get {
                return ResourceManager.GetString("UnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * To all messages sent to numbers of type &quot;U MTS&quot; will be added unsubscription text: .
        /// </summary>
        public static string UnsubTextMts {
            get {
                return ResourceManager.GetString("UnsubTextMts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** To all messages sent to numbers of type &quot;VAN MTS&quot; will be added unsubscription text:.
        /// </summary>
        public static string UnsubTextNotInMts {
            get {
                return ResourceManager.GetString("UnsubTextNotInMts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload data.
        /// </summary>
        public static string UploadData {
            get {
                return ResourceManager.GetString("UploadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload list of numbers.
        /// </summary>
        public static string UploadNumbers {
            get {
                return ResourceManager.GetString("UploadNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number/s to upload have not arrived! Try again later or contact your administrator..
        /// </summary>
        public static string UploadTableNumbersFail {
            get {
                return ResourceManager.GetString("UploadTableNumbersFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already unsubscribed!.
        /// </summary>
        public static string UserAlreadyUnsubscribed {
            get {
                return ResourceManager.GetString("UserAlreadyUnsubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully.
        /// </summary>
        public static string UserCreatedSuccessfully {
            get {
                return ResourceManager.GetString("UserCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted user.
        /// </summary>
        public static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this username is deleted. Please log in with valid username..
        /// </summary>
        public static string UserDeletedMessage {
            get {
                return ResourceManager.GetString("UserDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string UsernameIsRequired {
            get {
                return ResourceManager.GetString("UsernameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated successfully.
        /// </summary>
        public static string UserUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UserUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phone Number.
        /// </summary>
        public static string VerifyOTP {
            get {
                return ResourceManager.GetString("VerifyOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN.
        /// </summary>
        public static string VPN {
            get {
                return ResourceManager.GetString("VPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong date.
        /// </summary>
        public static string WrongDate {
            get {
                return ResourceManager.GetString("WrongDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
