//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizSMS.SelfCareLdapWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SelfCareLdapWS.LDAPCheckSoap")]
    public interface LDAPCheckSoap {
        
        // CODEGEN: Generating message contract since element name msisdn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vratiTipKorisnika", ReplyAction="*")]
        BizSMS.SelfCareLdapWS.vratiTipKorisnikaResponse vratiTipKorisnika(BizSMS.SelfCareLdapWS.vratiTipKorisnikaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vratiTipKorisnika", ReplyAction="*")]
        System.Threading.Tasks.Task<BizSMS.SelfCareLdapWS.vratiTipKorisnikaResponse> vratiTipKorisnikaAsync(BizSMS.SelfCareLdapWS.vratiTipKorisnikaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class vratiTipKorisnikaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="vratiTipKorisnika", Namespace="http://tempuri.org/", Order=0)]
        public BizSMS.SelfCareLdapWS.vratiTipKorisnikaRequestBody Body;
        
        public vratiTipKorisnikaRequest() {
        }
        
        public vratiTipKorisnikaRequest(BizSMS.SelfCareLdapWS.vratiTipKorisnikaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class vratiTipKorisnikaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string msisdn;
        
        public vratiTipKorisnikaRequestBody() {
        }
        
        public vratiTipKorisnikaRequestBody(string msisdn) {
            this.msisdn = msisdn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class vratiTipKorisnikaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="vratiTipKorisnikaResponse", Namespace="http://tempuri.org/", Order=0)]
        public BizSMS.SelfCareLdapWS.vratiTipKorisnikaResponseBody Body;
        
        public vratiTipKorisnikaResponse() {
        }
        
        public vratiTipKorisnikaResponse(BizSMS.SelfCareLdapWS.vratiTipKorisnikaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class vratiTipKorisnikaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vratiTipKorisnikaResult;
        
        public vratiTipKorisnikaResponseBody() {
        }
        
        public vratiTipKorisnikaResponseBody(string vratiTipKorisnikaResult) {
            this.vratiTipKorisnikaResult = vratiTipKorisnikaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LDAPCheckSoapChannel : BizSMS.SelfCareLdapWS.LDAPCheckSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LDAPCheckSoapClient : System.ServiceModel.ClientBase<BizSMS.SelfCareLdapWS.LDAPCheckSoap>, BizSMS.SelfCareLdapWS.LDAPCheckSoap {
        
        public LDAPCheckSoapClient() {
        }
        
        public LDAPCheckSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LDAPCheckSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LDAPCheckSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LDAPCheckSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BizSMS.SelfCareLdapWS.vratiTipKorisnikaResponse BizSMS.SelfCareLdapWS.LDAPCheckSoap.vratiTipKorisnika(BizSMS.SelfCareLdapWS.vratiTipKorisnikaRequest request) {
            return base.Channel.vratiTipKorisnika(request);
        }
        
        public string vratiTipKorisnika(string msisdn) {
            BizSMS.SelfCareLdapWS.vratiTipKorisnikaRequest inValue = new BizSMS.SelfCareLdapWS.vratiTipKorisnikaRequest();
            inValue.Body = new BizSMS.SelfCareLdapWS.vratiTipKorisnikaRequestBody();
            inValue.Body.msisdn = msisdn;
            BizSMS.SelfCareLdapWS.vratiTipKorisnikaResponse retVal = ((BizSMS.SelfCareLdapWS.LDAPCheckSoap)(this)).vratiTipKorisnika(inValue);
            return retVal.Body.vratiTipKorisnikaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BizSMS.SelfCareLdapWS.vratiTipKorisnikaResponse> BizSMS.SelfCareLdapWS.LDAPCheckSoap.vratiTipKorisnikaAsync(BizSMS.SelfCareLdapWS.vratiTipKorisnikaRequest request) {
            return base.Channel.vratiTipKorisnikaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BizSMS.SelfCareLdapWS.vratiTipKorisnikaResponse> vratiTipKorisnikaAsync(string msisdn) {
            BizSMS.SelfCareLdapWS.vratiTipKorisnikaRequest inValue = new BizSMS.SelfCareLdapWS.vratiTipKorisnikaRequest();
            inValue.Body = new BizSMS.SelfCareLdapWS.vratiTipKorisnikaRequestBody();
            inValue.Body.msisdn = msisdn;
            return ((BizSMS.SelfCareLdapWS.LDAPCheckSoap)(this)).vratiTipKorisnikaAsync(inValue);
        }
    }
}
