//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnsubBizSMSWebService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vassdpqa.telekom.rs:8780/SubscriptionManagerService/services/Sdp")]
        public string UnsubBizSMSWebService_yu_telekom_it_kasdpca2test_SdpService {
            get {
                return ((string)(this["UnsubBizSMSWebService_yu_telekom_it_kasdpca2test_SdpService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vassdpqa.telekom.rs:27010/ParlayXSmsAccess/services/SendSms")]
        public string UnsubBizSMSWebService_SendSMSReference_SendSmsService {
            get {
                return ((string)(this["UnsubBizSMSWebService_SendSMSReference_SendSmsService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wsselfcaretest.telekom.rs/mailservice.asmx")]
        public string UnsubBizSMSWebService_SendEmailReference_MailService {
            get {
                return ((string)(this["UnsubBizSMSWebService_SendEmailReference_MailService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://kavasraz/http2sms/http2sms.asmx")]
        public string UnsubBizSMSWebService_SendSMShttp2sms_http2sms {
            get {
                return ((string)(this["UnsubBizSMSWebService_SendSMShttp2sms_http2sms"]));
            }
        }
    }
}
