//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace UnsubBizSMSWebService.SendEmailReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MailServiceSoap", Namespace="http://tempuri.org/")]
    public partial class MailService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendEmailWithBccOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendEmailWithAttOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MailService() {
            this.Url = global::UnsubBizSMSWebService.Properties.Settings.Default.UnsubBizSMSWebService_SendEmailReference_MailService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendEmailCompletedEventHandler SendEmailCompleted;
        
        /// <remarks/>
        public event SendEmailWithBccCompletedEventHandler SendEmailWithBccCompleted;
        
        /// <remarks/>
        public event SendEmailWithAttCompletedEventHandler SendEmailWithAttCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendEmail(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string subject, string body) {
            object[] results = this.Invoke("SendEmail", new object[] {
                        fromAddress,
                        fromName,
                        toAddress,
                        toName,
                        ccAddress,
                        ccName,
                        subject,
                        body});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendEmailAsync(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string subject, string body) {
            this.SendEmailAsync(fromAddress, fromName, toAddress, toName, ccAddress, ccName, subject, body, null);
        }
        
        /// <remarks/>
        public void SendEmailAsync(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string subject, string body, object userState) {
            if ((this.SendEmailOperationCompleted == null)) {
                this.SendEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailOperationCompleted);
            }
            this.InvokeAsync("SendEmail", new object[] {
                        fromAddress,
                        fromName,
                        toAddress,
                        toName,
                        ccAddress,
                        ccName,
                        subject,
                        body}, this.SendEmailOperationCompleted, userState);
        }
        
        private void OnSendEmailOperationCompleted(object arg) {
            if ((this.SendEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailCompleted(this, new SendEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmailWithBcc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendEmailWithBcc(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string bccAddress, string bccName, string subject, string body) {
            object[] results = this.Invoke("SendEmailWithBcc", new object[] {
                        fromAddress,
                        fromName,
                        toAddress,
                        toName,
                        ccAddress,
                        ccName,
                        bccAddress,
                        bccName,
                        subject,
                        body});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendEmailWithBccAsync(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string bccAddress, string bccName, string subject, string body) {
            this.SendEmailWithBccAsync(fromAddress, fromName, toAddress, toName, ccAddress, ccName, bccAddress, bccName, subject, body, null);
        }
        
        /// <remarks/>
        public void SendEmailWithBccAsync(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string bccAddress, string bccName, string subject, string body, object userState) {
            if ((this.SendEmailWithBccOperationCompleted == null)) {
                this.SendEmailWithBccOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailWithBccOperationCompleted);
            }
            this.InvokeAsync("SendEmailWithBcc", new object[] {
                        fromAddress,
                        fromName,
                        toAddress,
                        toName,
                        ccAddress,
                        ccName,
                        bccAddress,
                        bccName,
                        subject,
                        body}, this.SendEmailWithBccOperationCompleted, userState);
        }
        
        private void OnSendEmailWithBccOperationCompleted(object arg) {
            if ((this.SendEmailWithBccCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailWithBccCompleted(this, new SendEmailWithBccCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmailWithAtt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendEmailWithAtt(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string bccAddress, string bccName, string subject, string body, MailPriority priority, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] bAtt, string attName) {
            object[] results = this.Invoke("SendEmailWithAtt", new object[] {
                        fromAddress,
                        fromName,
                        toAddress,
                        toName,
                        ccAddress,
                        ccName,
                        bccAddress,
                        bccName,
                        subject,
                        body,
                        priority,
                        bAtt,
                        attName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendEmailWithAttAsync(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string bccAddress, string bccName, string subject, string body, MailPriority priority, byte[] bAtt, string attName) {
            this.SendEmailWithAttAsync(fromAddress, fromName, toAddress, toName, ccAddress, ccName, bccAddress, bccName, subject, body, priority, bAtt, attName, null);
        }
        
        /// <remarks/>
        public void SendEmailWithAttAsync(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string bccAddress, string bccName, string subject, string body, MailPriority priority, byte[] bAtt, string attName, object userState) {
            if ((this.SendEmailWithAttOperationCompleted == null)) {
                this.SendEmailWithAttOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailWithAttOperationCompleted);
            }
            this.InvokeAsync("SendEmailWithAtt", new object[] {
                        fromAddress,
                        fromName,
                        toAddress,
                        toName,
                        ccAddress,
                        ccName,
                        bccAddress,
                        bccName,
                        subject,
                        body,
                        priority,
                        bAtt,
                        attName}, this.SendEmailWithAttOperationCompleted, userState);
        }
        
        private void OnSendEmailWithAttOperationCompleted(object arg) {
            if ((this.SendEmailWithAttCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailWithAttCompleted(this, new SendEmailWithAttCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum MailPriority {
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        Low,
        
        /// <remarks/>
        High,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendEmailCompletedEventHandler(object sender, SendEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendEmailWithBccCompletedEventHandler(object sender, SendEmailWithBccCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendEmailWithBccCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendEmailWithBccCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendEmailWithAttCompletedEventHandler(object sender, SendEmailWithAttCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendEmailWithAttCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendEmailWithAttCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591