//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnsubBizSMSWebService.SelfCareEmailWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SelfCareEmailWS.MailServiceSoap")]
    public interface MailServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SendEmail(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string subject, string body);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SendEmail", ReplyAction="*")]
        System.IAsyncResult BeginSendEmail(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string subject, string body, System.AsyncCallback callback, object asyncState);
        
        bool EndSendEmail(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmailWithBcc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SendEmailWithBcc(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string bccAddress, string bccName, string subject, string body);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SendEmailWithBcc", ReplyAction="*")]
        System.IAsyncResult BeginSendEmailWithBcc(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string bccAddress, string bccName, string subject, string body, System.AsyncCallback callback, object asyncState);
        
        bool EndSendEmailWithBcc(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'bAtt' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmailWithAtt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UnsubBizSMSWebService.SelfCareEmailWS.SendEmailWithAttResponse SendEmailWithAtt(UnsubBizSMSWebService.SelfCareEmailWS.SendEmailWithAttRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SendEmailWithAtt", ReplyAction="*")]
        System.IAsyncResult BeginSendEmailWithAtt(UnsubBizSMSWebService.SelfCareEmailWS.SendEmailWithAttRequest request, System.AsyncCallback callback, object asyncState);
        
        UnsubBizSMSWebService.SelfCareEmailWS.SendEmailWithAttResponse EndSendEmailWithAtt(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum MailPriority {
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        Low,
        
        /// <remarks/>
        High,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailWithAtt", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailWithAttRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string fromAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fromName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string toAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string toName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string ccAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string ccName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string bccAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string bccName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public UnsubBizSMSWebService.SelfCareEmailWS.MailPriority priority;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bAtt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string attName;
        
        public SendEmailWithAttRequest() {
        }
        
        public SendEmailWithAttRequest(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string bccAddress, string bccName, string subject, string body, UnsubBizSMSWebService.SelfCareEmailWS.MailPriority priority, byte[] bAtt, string attName) {
            this.fromAddress = fromAddress;
            this.fromName = fromName;
            this.toAddress = toAddress;
            this.toName = toName;
            this.ccAddress = ccAddress;
            this.ccName = ccName;
            this.bccAddress = bccAddress;
            this.bccName = bccName;
            this.subject = subject;
            this.body = body;
            this.priority = priority;
            this.bAtt = bAtt;
            this.attName = attName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailWithAttResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailWithAttResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SendEmailWithAttResult;
        
        public SendEmailWithAttResponse() {
        }
        
        public SendEmailWithAttResponse(bool SendEmailWithAttResult) {
            this.SendEmailWithAttResult = SendEmailWithAttResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MailServiceSoapChannel : UnsubBizSMSWebService.SelfCareEmailWS.MailServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SendEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendEmailWithBccCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SendEmailWithBccCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendEmailWithAttCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SendEmailWithAttCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailServiceSoapClient : System.ServiceModel.ClientBase<UnsubBizSMSWebService.SelfCareEmailWS.MailServiceSoap>, UnsubBizSMSWebService.SelfCareEmailWS.MailServiceSoap {
        
        private BeginOperationDelegate onBeginSendEmailDelegate;
        
        private EndOperationDelegate onEndSendEmailDelegate;
        
        private System.Threading.SendOrPostCallback onSendEmailCompletedDelegate;
        
        private BeginOperationDelegate onBeginSendEmailWithBccDelegate;
        
        private EndOperationDelegate onEndSendEmailWithBccDelegate;
        
        private System.Threading.SendOrPostCallback onSendEmailWithBccCompletedDelegate;
        
        private BeginOperationDelegate onBeginSendEmailWithAttDelegate;
        
        private EndOperationDelegate onEndSendEmailWithAttDelegate;
        
        private System.Threading.SendOrPostCallback onSendEmailWithAttCompletedDelegate;
        
        public MailServiceSoapClient() {
        }
        
        public MailServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<SendEmailCompletedEventArgs> SendEmailCompleted;
        
        public event System.EventHandler<SendEmailWithBccCompletedEventArgs> SendEmailWithBccCompleted;
        
        public event System.EventHandler<SendEmailWithAttCompletedEventArgs> SendEmailWithAttCompleted;
        
        public bool SendEmail(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string subject, string body) {
            return base.Channel.SendEmail(fromAddress, fromName, toAddress, toName, ccAddress, ccName, subject, body);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSendEmail(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string subject, string body, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSendEmail(fromAddress, fromName, toAddress, toName, ccAddress, ccName, subject, body, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndSendEmail(System.IAsyncResult result) {
            return base.Channel.EndSendEmail(result);
        }
        
        private System.IAsyncResult OnBeginSendEmail(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string fromAddress = ((string)(inValues[0]));
            string fromName = ((string)(inValues[1]));
            string toAddress = ((string)(inValues[2]));
            string toName = ((string)(inValues[3]));
            string ccAddress = ((string)(inValues[4]));
            string ccName = ((string)(inValues[5]));
            string subject = ((string)(inValues[6]));
            string body = ((string)(inValues[7]));
            return this.BeginSendEmail(fromAddress, fromName, toAddress, toName, ccAddress, ccName, subject, body, callback, asyncState);
        }
        
        private object[] OnEndSendEmail(System.IAsyncResult result) {
            bool retVal = this.EndSendEmail(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSendEmailCompleted(object state) {
            if ((this.SendEmailCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SendEmailCompleted(this, new SendEmailCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SendEmailAsync(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string subject, string body) {
            this.SendEmailAsync(fromAddress, fromName, toAddress, toName, ccAddress, ccName, subject, body, null);
        }
        
        public void SendEmailAsync(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string subject, string body, object userState) {
            if ((this.onBeginSendEmailDelegate == null)) {
                this.onBeginSendEmailDelegate = new BeginOperationDelegate(this.OnBeginSendEmail);
            }
            if ((this.onEndSendEmailDelegate == null)) {
                this.onEndSendEmailDelegate = new EndOperationDelegate(this.OnEndSendEmail);
            }
            if ((this.onSendEmailCompletedDelegate == null)) {
                this.onSendEmailCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSendEmailCompleted);
            }
            base.InvokeAsync(this.onBeginSendEmailDelegate, new object[] {
                        fromAddress,
                        fromName,
                        toAddress,
                        toName,
                        ccAddress,
                        ccName,
                        subject,
                        body}, this.onEndSendEmailDelegate, this.onSendEmailCompletedDelegate, userState);
        }
        
        public bool SendEmailWithBcc(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string bccAddress, string bccName, string subject, string body) {
            return base.Channel.SendEmailWithBcc(fromAddress, fromName, toAddress, toName, ccAddress, ccName, bccAddress, bccName, subject, body);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSendEmailWithBcc(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string bccAddress, string bccName, string subject, string body, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSendEmailWithBcc(fromAddress, fromName, toAddress, toName, ccAddress, ccName, bccAddress, bccName, subject, body, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndSendEmailWithBcc(System.IAsyncResult result) {
            return base.Channel.EndSendEmailWithBcc(result);
        }
        
        private System.IAsyncResult OnBeginSendEmailWithBcc(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string fromAddress = ((string)(inValues[0]));
            string fromName = ((string)(inValues[1]));
            string toAddress = ((string)(inValues[2]));
            string toName = ((string)(inValues[3]));
            string ccAddress = ((string)(inValues[4]));
            string ccName = ((string)(inValues[5]));
            string bccAddress = ((string)(inValues[6]));
            string bccName = ((string)(inValues[7]));
            string subject = ((string)(inValues[8]));
            string body = ((string)(inValues[9]));
            return this.BeginSendEmailWithBcc(fromAddress, fromName, toAddress, toName, ccAddress, ccName, bccAddress, bccName, subject, body, callback, asyncState);
        }
        
        private object[] OnEndSendEmailWithBcc(System.IAsyncResult result) {
            bool retVal = this.EndSendEmailWithBcc(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSendEmailWithBccCompleted(object state) {
            if ((this.SendEmailWithBccCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SendEmailWithBccCompleted(this, new SendEmailWithBccCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SendEmailWithBccAsync(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string bccAddress, string bccName, string subject, string body) {
            this.SendEmailWithBccAsync(fromAddress, fromName, toAddress, toName, ccAddress, ccName, bccAddress, bccName, subject, body, null);
        }
        
        public void SendEmailWithBccAsync(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string bccAddress, string bccName, string subject, string body, object userState) {
            if ((this.onBeginSendEmailWithBccDelegate == null)) {
                this.onBeginSendEmailWithBccDelegate = new BeginOperationDelegate(this.OnBeginSendEmailWithBcc);
            }
            if ((this.onEndSendEmailWithBccDelegate == null)) {
                this.onEndSendEmailWithBccDelegate = new EndOperationDelegate(this.OnEndSendEmailWithBcc);
            }
            if ((this.onSendEmailWithBccCompletedDelegate == null)) {
                this.onSendEmailWithBccCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSendEmailWithBccCompleted);
            }
            base.InvokeAsync(this.onBeginSendEmailWithBccDelegate, new object[] {
                        fromAddress,
                        fromName,
                        toAddress,
                        toName,
                        ccAddress,
                        ccName,
                        bccAddress,
                        bccName,
                        subject,
                        body}, this.onEndSendEmailWithBccDelegate, this.onSendEmailWithBccCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnsubBizSMSWebService.SelfCareEmailWS.SendEmailWithAttResponse UnsubBizSMSWebService.SelfCareEmailWS.MailServiceSoap.SendEmailWithAtt(UnsubBizSMSWebService.SelfCareEmailWS.SendEmailWithAttRequest request) {
            return base.Channel.SendEmailWithAtt(request);
        }
        
        public bool SendEmailWithAtt(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string bccAddress, string bccName, string subject, string body, UnsubBizSMSWebService.SelfCareEmailWS.MailPriority priority, byte[] bAtt, string attName) {
            UnsubBizSMSWebService.SelfCareEmailWS.SendEmailWithAttRequest inValue = new UnsubBizSMSWebService.SelfCareEmailWS.SendEmailWithAttRequest();
            inValue.fromAddress = fromAddress;
            inValue.fromName = fromName;
            inValue.toAddress = toAddress;
            inValue.toName = toName;
            inValue.ccAddress = ccAddress;
            inValue.ccName = ccName;
            inValue.bccAddress = bccAddress;
            inValue.bccName = bccName;
            inValue.subject = subject;
            inValue.body = body;
            inValue.priority = priority;
            inValue.bAtt = bAtt;
            inValue.attName = attName;
            UnsubBizSMSWebService.SelfCareEmailWS.SendEmailWithAttResponse retVal = ((UnsubBizSMSWebService.SelfCareEmailWS.MailServiceSoap)(this)).SendEmailWithAtt(inValue);
            return retVal.SendEmailWithAttResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UnsubBizSMSWebService.SelfCareEmailWS.MailServiceSoap.BeginSendEmailWithAtt(UnsubBizSMSWebService.SelfCareEmailWS.SendEmailWithAttRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSendEmailWithAtt(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSendEmailWithAtt(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string bccAddress, string bccName, string subject, string body, UnsubBizSMSWebService.SelfCareEmailWS.MailPriority priority, byte[] bAtt, string attName, System.AsyncCallback callback, object asyncState) {
            UnsubBizSMSWebService.SelfCareEmailWS.SendEmailWithAttRequest inValue = new UnsubBizSMSWebService.SelfCareEmailWS.SendEmailWithAttRequest();
            inValue.fromAddress = fromAddress;
            inValue.fromName = fromName;
            inValue.toAddress = toAddress;
            inValue.toName = toName;
            inValue.ccAddress = ccAddress;
            inValue.ccName = ccName;
            inValue.bccAddress = bccAddress;
            inValue.bccName = bccName;
            inValue.subject = subject;
            inValue.body = body;
            inValue.priority = priority;
            inValue.bAtt = bAtt;
            inValue.attName = attName;
            return ((UnsubBizSMSWebService.SelfCareEmailWS.MailServiceSoap)(this)).BeginSendEmailWithAtt(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnsubBizSMSWebService.SelfCareEmailWS.SendEmailWithAttResponse UnsubBizSMSWebService.SelfCareEmailWS.MailServiceSoap.EndSendEmailWithAtt(System.IAsyncResult result) {
            return base.Channel.EndSendEmailWithAtt(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndSendEmailWithAtt(System.IAsyncResult result) {
            UnsubBizSMSWebService.SelfCareEmailWS.SendEmailWithAttResponse retVal = ((UnsubBizSMSWebService.SelfCareEmailWS.MailServiceSoap)(this)).EndSendEmailWithAtt(result);
            return retVal.SendEmailWithAttResult;
        }
        
        private System.IAsyncResult OnBeginSendEmailWithAtt(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string fromAddress = ((string)(inValues[0]));
            string fromName = ((string)(inValues[1]));
            string toAddress = ((string)(inValues[2]));
            string toName = ((string)(inValues[3]));
            string ccAddress = ((string)(inValues[4]));
            string ccName = ((string)(inValues[5]));
            string bccAddress = ((string)(inValues[6]));
            string bccName = ((string)(inValues[7]));
            string subject = ((string)(inValues[8]));
            string body = ((string)(inValues[9]));
            UnsubBizSMSWebService.SelfCareEmailWS.MailPriority priority = ((UnsubBizSMSWebService.SelfCareEmailWS.MailPriority)(inValues[10]));
            byte[] bAtt = ((byte[])(inValues[11]));
            string attName = ((string)(inValues[12]));
            return this.BeginSendEmailWithAtt(fromAddress, fromName, toAddress, toName, ccAddress, ccName, bccAddress, bccName, subject, body, priority, bAtt, attName, callback, asyncState);
        }
        
        private object[] OnEndSendEmailWithAtt(System.IAsyncResult result) {
            bool retVal = this.EndSendEmailWithAtt(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSendEmailWithAttCompleted(object state) {
            if ((this.SendEmailWithAttCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SendEmailWithAttCompleted(this, new SendEmailWithAttCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SendEmailWithAttAsync(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string bccAddress, string bccName, string subject, string body, UnsubBizSMSWebService.SelfCareEmailWS.MailPriority priority, byte[] bAtt, string attName) {
            this.SendEmailWithAttAsync(fromAddress, fromName, toAddress, toName, ccAddress, ccName, bccAddress, bccName, subject, body, priority, bAtt, attName, null);
        }
        
        public void SendEmailWithAttAsync(string fromAddress, string fromName, string toAddress, string toName, string ccAddress, string ccName, string bccAddress, string bccName, string subject, string body, UnsubBizSMSWebService.SelfCareEmailWS.MailPriority priority, byte[] bAtt, string attName, object userState) {
            if ((this.onBeginSendEmailWithAttDelegate == null)) {
                this.onBeginSendEmailWithAttDelegate = new BeginOperationDelegate(this.OnBeginSendEmailWithAtt);
            }
            if ((this.onEndSendEmailWithAttDelegate == null)) {
                this.onEndSendEmailWithAttDelegate = new EndOperationDelegate(this.OnEndSendEmailWithAtt);
            }
            if ((this.onSendEmailWithAttCompletedDelegate == null)) {
                this.onSendEmailWithAttCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSendEmailWithAttCompleted);
            }
            base.InvokeAsync(this.onBeginSendEmailWithAttDelegate, new object[] {
                        fromAddress,
                        fromName,
                        toAddress,
                        toName,
                        ccAddress,
                        ccName,
                        bccAddress,
                        bccName,
                        subject,
                        body,
                        priority,
                        bAtt,
                        attName}, this.onEndSendEmailWithAttDelegate, this.onSendEmailWithAttCompletedDelegate, userState);
        }
    }
}
