// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserId_FK_Removed_from_Group : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserId_FK_Removed_from_Group));
        
        string IMigrationMetadata.Id
        {
            get { return "201701261150472_UserId_FK_Removed_from_Group"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
