// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Default_field_added_in_Group_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Default_field_added_in_Group_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201701311000012_Default_field_added_in_Group_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
