// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class name_field_added_to_temp_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(name_field_added_to_temp_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201712191231268_name_field_added_to_temp_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
