// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Delivered_data_type_int : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Delivered_data_type_int));
        
        string IMigrationMetadata.Id
        {
            get { return "201706210717479_Delivered_data_type_int"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
