// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sent_field_to_MessageNumber_and_test_field_to_Message : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sent_field_to_MessageNumber_and_test_field_to_Message));
        
        string IMigrationMetadata.Id
        {
            get { return "201705112022519_sent_field_to_MessageNumber_and_test_field_to_Message"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
