// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class start_date_added_to_message_cost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(start_date_added_to_message_cost));
        
        string IMigrationMetadata.Id
        {
            get { return "201705132210453_start_date_added_to_message_cost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
