// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class client_id_added_to_numbers_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(client_id_added_to_numbers_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201702061751331_client_id_added_to_numbers_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
