// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MessageCost_FK_removed_from_MessageNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MessageCost_FK_removed_from_MessageNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "201702200718038_MessageCost_FK_removed_from_MessageNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
