// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsCanceled_added_to_Client_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsCanceled_added_to_Client_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201701171440180_IsCanceled_added_to_Client_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
