// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_linked_to_messages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_linked_to_messages));
        
        string IMigrationMetadata.Id
        {
            get { return "201703011117357_User_linked_to_messages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
