// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class number_type_added_to_message_number : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(number_type_added_to_message_number));
        
        string IMigrationMetadata.Id
        {
            get { return "201705132137477_number_type_added_to_message_number"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
