// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MessageCostId_FK_in_MessageNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MessageCostId_FK_in_MessageNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "201705111942478_MessageCostId_FK_in_MessageNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
