// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TableName_for_client_contracts_modified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableName_for_client_contracts_modified));
        
        string IMigrationMetadata.Id
        {
            get { return "201811021231424_TableName_for_client_contracts_modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
