// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SynchronizationDate_added_to_ClientContracts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SynchronizationDate_added_to_ClientContracts));
        
        string IMigrationMetadata.Id
        {
            get { return "201811211457583_SynchronizationDate_added_to_ClientContracts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
