// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ContractId_added_to_NumberModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContractId_added_to_NumberModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201811222040078_ContractId_added_to_NumberModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
