// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Charged_property_added_to_message_and_messageNumber_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Charged_property_added_to_message_and_messageNumber_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201811101813025_Charged_property_added_to_message_and_messageNumber_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
