// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fix_GropupId_column_name_in_tempImport_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_GropupId_column_name_in_tempImport_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202001211253493_fix_GropupId_column_name_in_tempImport_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
