// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class scheduled_sms_model_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(scheduled_sms_model_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202004191822022_scheduled_sms_model_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
