// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SendAllowed_added_to_DenySendingReason : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SendAllowed_added_to_DenySendingReason));
        
        string IMigrationMetadata.Id
        {
            get { return "202002121451272_SendAllowed_added_to_DenySendingReason"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
