// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changed_column_name_MessageNumberTypeLength_to_MessageLengthNT_in_MessageNumber_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changed_column_name_MessageNumberTypeLength_to_MessageLengthNT_in_MessageNumber_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202008201546092_Changed_column_name_MessageNumberTypeLength_to_MessageLengthNT_in_MessageNumber_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
