// <auto-generated />
namespace BizSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_User_Cancel_to_foreign_key_in_ScheduledSms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_User_Cancel_to_foreign_key_in_ScheduledSms));
        
        string IMigrationMetadata.Id
        {
            get { return "202004281204520_change_User_Cancel_to_foreign_key_in_ScheduledSms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
