//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace UnsubBizSMSWebService.SendSMSReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SendSmsSoapBinding", Namespace="http://www.csapi.org/wsdl/parlayx/sms/send/v2_1/service")]
    public partial class SendSmsService : Microsoft.Web.Services3.WebServicesClientProtocol
    {
        
        private System.Threading.SendOrPostCallback sendSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendSmsLogoOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendSmsRingtoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSmsDeliveryStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SendSmsService() {
            this.Url = global::UnsubBizSMSWebService.Properties.Settings.Default.UnsubBizSMSWebService_SendSMSReference_SendSmsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sendSmsCompletedEventHandler sendSmsCompleted;
        
        /// <remarks/>
        public event sendSmsLogoCompletedEventHandler sendSmsLogoCompleted;
        
        /// <remarks/>
        public event sendSmsRingtoneCompletedEventHandler sendSmsRingtoneCompleted;
        
        /// <remarks/>
        public event getSmsDeliveryStatusCompletedEventHandler getSmsDeliveryStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.csapi.org/schema/parlayx/sms/send/v2_1/local", ResponseNamespace="http://www.csapi.org/schema/parlayx/sms/send/v2_1/local", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public string sendSms([System.Xml.Serialization.XmlElementAttribute("addresses", DataType="anyURI")] string[] addresses, string senderName, ChargingInformation charging, string message, SimpleReference receiptRequest) {
            object[] results = this.Invoke("sendSms", new object[] {
                        addresses,
                        senderName,
                        charging,
                        message,
                        receiptRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendSmsAsync(string[] addresses, string senderName, ChargingInformation charging, string message, SimpleReference receiptRequest) {
            this.sendSmsAsync(addresses, senderName, charging, message, receiptRequest, null);
        }
        
        /// <remarks/>
        public void sendSmsAsync(string[] addresses, string senderName, ChargingInformation charging, string message, SimpleReference receiptRequest, object userState) {
            if ((this.sendSmsOperationCompleted == null)) {
                this.sendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendSmsOperationCompleted);
            }
            this.InvokeAsync("sendSms", new object[] {
                        addresses,
                        senderName,
                        charging,
                        message,
                        receiptRequest}, this.sendSmsOperationCompleted, userState);
        }
        
        private void OnsendSmsOperationCompleted(object arg) {
            if ((this.sendSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendSmsCompleted(this, new sendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.csapi.org/schema/parlayx/sms/send/v2_1/local", ResponseNamespace="http://www.csapi.org/schema/parlayx/sms/send/v2_1/local", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public string sendSmsLogo([System.Xml.Serialization.XmlElementAttribute("addresses", DataType="anyURI")] string[] addresses, string senderName, ChargingInformation charging, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] image, SmsFormat smsFormat, SimpleReference receiptRequest) {
            object[] results = this.Invoke("sendSmsLogo", new object[] {
                        addresses,
                        senderName,
                        charging,
                        image,
                        smsFormat,
                        receiptRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendSmsLogoAsync(string[] addresses, string senderName, ChargingInformation charging, byte[] image, SmsFormat smsFormat, SimpleReference receiptRequest) {
            this.sendSmsLogoAsync(addresses, senderName, charging, image, smsFormat, receiptRequest, null);
        }
        
        /// <remarks/>
        public void sendSmsLogoAsync(string[] addresses, string senderName, ChargingInformation charging, byte[] image, SmsFormat smsFormat, SimpleReference receiptRequest, object userState) {
            if ((this.sendSmsLogoOperationCompleted == null)) {
                this.sendSmsLogoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendSmsLogoOperationCompleted);
            }
            this.InvokeAsync("sendSmsLogo", new object[] {
                        addresses,
                        senderName,
                        charging,
                        image,
                        smsFormat,
                        receiptRequest}, this.sendSmsLogoOperationCompleted, userState);
        }
        
        private void OnsendSmsLogoOperationCompleted(object arg) {
            if ((this.sendSmsLogoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendSmsLogoCompleted(this, new sendSmsLogoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.csapi.org/schema/parlayx/sms/send/v2_1/local", ResponseNamespace="http://www.csapi.org/schema/parlayx/sms/send/v2_1/local", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public string sendSmsRingtone([System.Xml.Serialization.XmlElementAttribute("addresses", DataType="anyURI")] string[] addresses, string senderName, ChargingInformation charging, string ringtone, SmsFormat smsFormat, SimpleReference receiptRequest) {
            object[] results = this.Invoke("sendSmsRingtone", new object[] {
                        addresses,
                        senderName,
                        charging,
                        ringtone,
                        smsFormat,
                        receiptRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendSmsRingtoneAsync(string[] addresses, string senderName, ChargingInformation charging, string ringtone, SmsFormat smsFormat, SimpleReference receiptRequest) {
            this.sendSmsRingtoneAsync(addresses, senderName, charging, ringtone, smsFormat, receiptRequest, null);
        }
        
        /// <remarks/>
        public void sendSmsRingtoneAsync(string[] addresses, string senderName, ChargingInformation charging, string ringtone, SmsFormat smsFormat, SimpleReference receiptRequest, object userState) {
            if ((this.sendSmsRingtoneOperationCompleted == null)) {
                this.sendSmsRingtoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendSmsRingtoneOperationCompleted);
            }
            this.InvokeAsync("sendSmsRingtone", new object[] {
                        addresses,
                        senderName,
                        charging,
                        ringtone,
                        smsFormat,
                        receiptRequest}, this.sendSmsRingtoneOperationCompleted, userState);
        }
        
        private void OnsendSmsRingtoneOperationCompleted(object arg) {
            if ((this.sendSmsRingtoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendSmsRingtoneCompleted(this, new sendSmsRingtoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.csapi.org/schema/parlayx/sms/send/v2_1/local", ResponseNamespace="http://www.csapi.org/schema/parlayx/sms/send/v2_1/local", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public DeliveryInformation[] getSmsDeliveryStatus(string requestIdentifier) {
            object[] results = this.Invoke("getSmsDeliveryStatus", new object[] {
                        requestIdentifier});
            return ((DeliveryInformation[])(results[0]));
        }
        
        /// <remarks/>
        public void getSmsDeliveryStatusAsync(string requestIdentifier) {
            this.getSmsDeliveryStatusAsync(requestIdentifier, null);
        }
        
        /// <remarks/>
        public void getSmsDeliveryStatusAsync(string requestIdentifier, object userState) {
            if ((this.getSmsDeliveryStatusOperationCompleted == null)) {
                this.getSmsDeliveryStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSmsDeliveryStatusOperationCompleted);
            }
            this.InvokeAsync("getSmsDeliveryStatus", new object[] {
                        requestIdentifier}, this.getSmsDeliveryStatusOperationCompleted, userState);
        }
        
        private void OngetSmsDeliveryStatusOperationCompleted(object arg) {
            if ((this.getSmsDeliveryStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSmsDeliveryStatusCompleted(this, new getSmsDeliveryStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/common/v2_1")]
    public partial class ChargingInformation {
        
        private string descriptionField;
        
        private string currencyField;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/v2_1")]
    public partial class DeliveryInformation {
        
        private string addressField;
        
        private DeliveryStatus deliveryStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DeliveryStatus deliveryStatus {
            get {
                return this.deliveryStatusField;
            }
            set {
                this.deliveryStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/v2_1")]
    public enum DeliveryStatus {
        
        /// <remarks/>
        DeliveredToNetwork,
        
        /// <remarks/>
        DeliveryUncertain,
        
        /// <remarks/>
        DeliveryImpossible,
        
        /// <remarks/>
        MessageWaiting,
        
        /// <remarks/>
        DeliveredToTerminal,
        
        /// <remarks/>
        DeliveryNotificationNotSupported,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/common/v2_1")]
    public partial class SimpleReference {
        
        private string endpointField;
        
        private string interfaceNameField;
        
        private string correlatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string endpoint {
            get {
                return this.endpointField;
            }
            set {
                this.endpointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string interfaceName {
            get {
                return this.interfaceNameField;
            }
            set {
                this.interfaceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correlator {
            get {
                return this.correlatorField;
            }
            set {
                this.correlatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/v2_1")]
    public enum SmsFormat {
        
        /// <remarks/>
        Ems,
        
        /// <remarks/>
        SmartMessaging,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void sendSmsCompletedEventHandler(object sender, sendSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void sendSmsLogoCompletedEventHandler(object sender, sendSmsLogoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendSmsLogoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendSmsLogoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void sendSmsRingtoneCompletedEventHandler(object sender, sendSmsRingtoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendSmsRingtoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendSmsRingtoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getSmsDeliveryStatusCompletedEventHandler(object sender, getSmsDeliveryStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSmsDeliveryStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSmsDeliveryStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeliveryInformation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeliveryInformation[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591